### ISSUE TITLE
Incorrect values in hypergeometric_2F1

### ISSUE THREAD

**Issue by amellnik** [JuliaMath/GSL.jl#76]
My coworker @nicolasdidier noticed this strange issue with `sf_hyperg_2F1` on half of the domain:

![image](https://user-images.githubusercontent.com/7132414/46427173-8fffe700-c6f5-11e8-8b61-6512065a59a5.png)

(I wasn't able to test it on 1.0 due to unsatisfiable package requirements.)  Is there any way this could be an issue with this package or is this definitely due to GSL?

**Comment by amellnik** [comment]
I'm reasonably sure that it's the same thing as this bug in GSL itself: http://lists.gnu.org/archive/html/bug-gsl/2015-09/msg00003.html . I'll keep this issue open to track when it's fixed upstream.

**Comment by simonbyrne** [comment]
It looks like it has been fixed upstream. This package is still using a quite old version of GSL, so should be upgraded.

**Comment by ludvigak** [comment]
This still appears to be an issue, even after switching to GSL 2.5. 
Interestingly, the error estimate provided by GSL is also completely off

```julia
using GSL, PyPlot, PyCall

x = 0:0.01:1
a, b, c = -1/4, 1/4, 1
out = sf_hyperg_2F1_e.(a, b, c, x)
gslval = [r.val for r in out]
gslerr = [r.err for r in out]
pyval = pyimport("scipy.special")[:hyp2f1](a, b, c, x)

subplot(2,1,1);
plot(x, gslval, ".", label="GSL value")
plot(x, pyval, "--", label="SciPy value")
legend(); grid(); title("sf_hyperg_2F1_e(-1/4, 1/4, 1, x)")
subplot(2,1,2);
semilogy(x, gslerr, ".", label="GSL error est")
legend(); grid()
```

![image](https://user-images.githubusercontent.com/11027507/48222751-35882500-e34a-11e8-906e-94bcf033f186.png)

**Comment by ludvigak** [comment]
That's too bad. There actually seems to be quite a few bug reports on gsl_sf_hyperg_2F1. Let's just hope they get fixed in a future version.

**Comment by inkydragon** [comment]
Seems to still not be fixed in GSL 2.8.

```jl
using GSL  # with GSL_jll = "2.8"
using UnicodePlots

x = 0:0.01:1
a, b, c = -1/4, 1/4, 1
out = sf_hyperg_2F1_e.(a, b, c, x)
gslval = [r.val for r in out]
gslerr = [r.err for r in out]

scatterplot(x, gslval)
scatterplot(x, gslerr)
```
![image](https://github.com/user-attachments/assets/6f42a908-4122-464c-bba4-be72772627cb)
